### ISSUE TITLE
Using ModelSelection results to choose fit with best num of breakpoints 

### ISSUE THREAD

**Issue by criscres** [chasmani/piecewise-regression#12]
ModelSelection is flagged as experimental, will we be able to do this soon? In the meantime, do you recommend bootstrapping and using Fit for different number of breakpoints and selecting model with highest R2? ModelSelection already seems to be doing precisely this (bootstrapping Fit and comparing across models internally), why is do you still suggest running it multiple times for robustness? Why is BIC the metric chosen in ModelSelection? (there is little justification in the documentation).

**Comment by chasmani** [comment]
Thank you for your comment. We flagged ModelSelection as experimental because of the points that you raised. The choice of how to select a model will depend on your specific requirements. We used the BIC to compare models. You may want to use something else, such as the AIC or you may want to do something else depending on domain knowledge. Our main motivation with labeling it as "Experimental" is to discourage people from blindly relying on the ModelSelection results, and to take care in interpretation. 

I think that it may be helpful to explain this in the documentation, and change the description from "Experimental" to something like "Opinionated". I will do this during the next changes.
