### ISSUE TITLE
Question about calculation of VV in breakpoint_fit in main.py

### ISSUE THREAD

**Issue by RianneSchouten** [chasmani/piecewise-regression#4]
Dear @chasmani,

Thank you for your work on piecewise-regression and thank you for referring to Muggeo's paper; it has been very helpful for me in understanding segmented regression. 

I was wondering whether you could explain to me why the calculation of VV in line 104 in breakpoint_fit in main.py in is like this?
`VV = [np.heaviside(self.xx - bp, 1) for bp in self.current_breakpoints]`

In Muggeo's paper, V seems to be the negative of the indicator function (end of page 3060) because it is the derivative. Why is it not necessary to take the negative when calculating VV?

I hope you can help me to further understand. Thank you,

Kind regards,

Rianne Schouten

**Comment by chasmani** [comment]
Hi Rianne

Its a good question. If I remember correctly it is because I defined the terms slightly differently to Muggeo. Looking at Muggeo's paper, just below equation 3 he defined gamma = Beta(psi-pis(0)) . I believe that I defined gamma as the negative of that (there was a good reason for that. So when you do the fit the two negatives cancel out to give the estimate in Muggeo's equation 7. 

I think that's right but I'm not sure, so do get back to me if it doesn't help.
